#!/bin/bash
#
# Run the initdb, then start solr in the foreground
set -e

rm -rf /opt/solr/server/solr/configsets/_default/conf/managed-schema
rm -rf /opt/solr/server/solr/configsets/_default/conf/solrconfig.xml

cp /opt/tmp/managed-schema /opt/solr/server/solr/configsets/_default/conf/managed-schema
cp /opt/tmp/solrconfig.xml /opt/solr/server/solr/configsets/_default/conf/solrconfig.xml

if [[ "$VERBOSE" = "yes" ]]; then
    set -x
fi

. /opt/docker-solr/scripts/run-initdb

if [[ -v SOLR_PORT ]] && ! grep -E -q '^[0-9]+$' <<<"${SOLR_PORT}"; then
  echo "Invalid SOLR_PORT=$SOLR_PORT environment variable specified"
  exit 1
fi

echo "Starting Solr $SOLR_VERSION"

exec solr -f "$@"
